export const colorIcon = [
  {name: "Android Studio", color: "3DDC84"},
  {name: "Angular", color: "0F0F11"},
  {name: "Bison", color: "-"},
  {name: "C", color: "A8B9CC"},
  {name: "C++", color: "00599C"},
  {name: "CMake", color: "064F8C"},
  {name: "Dart", color: "0175C2"},
  {name: "Fastify", color: "000000"},
  {name: "Figma", color: "F24E1E"},
  {name: "Firebase", color: "DD2C00"},
  {name: "Flex", color: "-"},
  {name: "Flutter", color: "02569B"},
  {name: "Github Actions", color: "2088FF"},
  {name: "GitLab", color: "FC6D26"},
  {name: "GNU Bash", color: "4EAA25"},
  {name: "Grafana", color: "F46800"},
  {name: "ICS", color: "-"},
  {name: "Ionic", color: "3880FF"},
  {name: "Java", color: "-"},
  {name: "JavaScript", color: "F7DF1E"},
  {name: "Jupyter", color: "F37626"},
  {name: "Kali Linux", color: "557C94"},
  {name: "Kibana", color: "005571"},
  {name: "Kubernetes", color: "326CE5"},
  {name: "Linux", color: "FCC624"},
  {name: "Loki", color: "F46800"},
  {name: "LoRa", color: "-"},
  {name: "Matomo", color: "3152A0"},
  {name: "Microcontrôleur", color: "-"},
  {name: "MicrosoftAzure", color: "0078D4"},
  {name: "MongoDB", color: "47A248"},
  {name: "MySQL", color: "4479A1"},
  {name: "Nginx", color: "009639"},
  {name: "Node.js", color: "5FA04E"},
  {name: "OpenSSL", color: "721412"},
  {name: "OpenVPN", color: "EA7E20"},
  {name: "Phaser", color: "-"},
  {name: "Powershell", color: "5391FE"},
  {name: "Prometheus", color: "E6522C"},
  {name: "Puppeteer", color: "40B5A4"},
  {name: "Python", color: "3776AB"},
  {name: "Raspberry Pi", color: "A22846"},
  {name: "React", color: "61DAFB"},
  {name: "Selenium", color: "43B02A"},
  {name: "SFML", color: "8CC445"},
  {name: "Snort", color: "F6A7AA"},
  {name: "TypeScript", color: "3178C6"},
  {name: "Ubuntu", color: "E95420"},
  {name: "VirtualBox", color: "183A61"},
  {name: "Visual Studio", color: "5C2D91"},
  {name: "Visual Studio Code", color: "007ACC"},
  {name: "Wireshark", color: "1679A7"},
]
