name: deploy
on:
  workflow_dispatch:
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_PRIVATE }}
        known_hosts: 'just-a-placeholder-so-we-dont-get-errors'
    - name: Use coturiv/setup-ionic
      uses: coturiv/setup-ionic@v1
    - name: Build
      run: ionic build --prod
    - name: Adding Known Hosts
      run: ssh-keyscan -p 22 -H ${{ secrets.SSH_HOST }}  >> ~/.ssh/known_hosts 
    - name: Deploy
      run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} 'cd /root/Swis-main/profiles && git pull origin main'
      
